// <auto-generated />
using System;
using APIBanHang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIBanHang.Migrations
{
    [DbContext(typeof(XyzContext))]
    partial class XyzContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIBanHang.Data.Account", b =>
                {
                    b.Property<string>("MaAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Passwords")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("passwords");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaAccount")
                        .HasName("PK__ACCOUNT__0A2B8E34B4280F2D");

                    b.ToTable("ACCOUNT", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Chitietdonhang", b =>
                {
                    b.Property<int>("SoHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("MaHang")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("MuaGiamGia")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<short?>("SoLuong")
                        .HasColumnType("smallint");

                    b.HasKey("SoHoaDon", "MaHang")
                        .HasName("PK__CHITIETD__C0B293E30148B623");

                    b.HasIndex("MaHang");

                    b.ToTable("CHITIETDONHANG", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Chitietmathang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<int?>("CanNang")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("GiaHang")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MauSac")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SoLuong")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHang")
                        .HasName("PK__CHITIETM__19C0DB1D3009AE8F");

                    b.ToTable("CHITIETMATHANG", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Dondathang", b =>
                {
                    b.Property<int>("SoHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<DateTime?>("NgayChuyenHang")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("NoiGiaoHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoHoaDon")
                        .HasName("PK__DONDATHA__012E9E52FD6D9ED9");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DONDATHANG", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Khachhang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fax")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SanPhamMua")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KHACHHAN__88D2F0E546A61CD6");

                    b.HasIndex("MaAccount");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Loaihang", b =>
                {
                    b.Property<string>("MaLoaiHang")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("TenLoaiHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLoaiHang")
                        .HasName("PK__LOAIHANG__5EEA4160B0D6C536");

                    b.ToTable("LOAIHANG", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Mathang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCongTy")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("MaLoaiHang")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("TenHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHang")
                        .HasName("PK__MATHANG__19C0DB1DBF3A2B6F");

                    b.HasIndex("MaCongTy");

                    b.HasIndex("MaLoaiHang");

                    b.ToTable("MATHANG", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Nhacungcap", b =>
                {
                    b.Property<string>("MaCongTy")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fax")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenCongTy")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TenGiaoDich")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaCongTy")
                        .HasName("PK__NHACUNGC__E452D3DB56A0B92D");

                    b.ToTable("NHACUNGCAP", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Data.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ho")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("MaAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayLamViec")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("Ten")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NHANVIEN__77B2CA47267B669C");

                    b.HasIndex("MaAccount");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("APIBanHang.Secure.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaAccount");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("APIBanHang.Data.Chitietdonhang", b =>
                {
                    b.HasOne("APIBanHang.Data.Mathang", "MaHangNavigation")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__MaHan__4D94879B");

                    b.HasOne("APIBanHang.Data.Dondathang", "SoHoaDonNavigation")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("SoHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDO__SoHoa__4CA06362");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("SoHoaDonNavigation");
                });

            modelBuilder.Entity("APIBanHang.Data.Dondathang", b =>
                {
                    b.HasOne("APIBanHang.Data.Khachhang", "MaKhachHangNavigation")
                        .WithMany("Dondathangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DONDATHAN__MaKha__48CFD27E");

                    b.HasOne("APIBanHang.Data.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("Dondathangs")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__DONDATHAN__MaNha__49C3F6B7");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("APIBanHang.Data.Khachhang", b =>
                {
                    b.HasOne("APIBanHang.Data.Account", "MaAccountNavigation")
                        .WithMany("Khachhangs")
                        .HasForeignKey("MaAccount")
                        .HasConstraintName("FK__KHACHHANG__Fax__398D8EEE");

                    b.Navigation("MaAccountNavigation");
                });

            modelBuilder.Entity("APIBanHang.Data.Mathang", b =>
                {
                    b.HasOne("APIBanHang.Data.Nhacungcap", "MaCongTyNavigation")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaCongTy")
                        .HasConstraintName("FK__MATHANG__MaCongT__4222D4EF");

                    b.HasOne("APIBanHang.Data.Chitietmathang", "ChitietmathangNavigation")
                        .WithMany()
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIBanHang.Data.Loaihang", "MaLoaiHangNavigation")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaLoaiHang")
                        .HasConstraintName("FK__MATHANG__MaLoaiH__4316F928");

                    b.Navigation("ChitietmathangNavigation");

                    b.Navigation("MaCongTyNavigation");

                    b.Navigation("MaLoaiHangNavigation");
                });

            modelBuilder.Entity("APIBanHang.Data.Nhanvien", b =>
                {
                    b.HasOne("APIBanHang.Data.Account", "MaAccountNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaAccount")
                        .HasConstraintName("FK__NHANVIEN__PhuCap__45F365D3");

                    b.Navigation("MaAccountNavigation");
                });

            modelBuilder.Entity("APIBanHang.Secure.Data.RefreshToken", b =>
                {
                    b.HasOne("APIBanHang.Data.Account", "account")
                        .WithMany()
                        .HasForeignKey("MaAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("APIBanHang.Data.Account", b =>
                {
                    b.Navigation("Khachhangs");

                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("APIBanHang.Data.Dondathang", b =>
                {
                    b.Navigation("Chitietdonhangs");
                });

            modelBuilder.Entity("APIBanHang.Data.Khachhang", b =>
                {
                    b.Navigation("Dondathangs");
                });

            modelBuilder.Entity("APIBanHang.Data.Loaihang", b =>
                {
                    b.Navigation("Mathangs");
                });

            modelBuilder.Entity("APIBanHang.Data.Mathang", b =>
                {
                    b.Navigation("Chitietdonhangs");
                });

            modelBuilder.Entity("APIBanHang.Data.Nhacungcap", b =>
                {
                    b.Navigation("Mathangs");
                });

            modelBuilder.Entity("APIBanHang.Data.Nhanvien", b =>
                {
                    b.Navigation("Dondathangs");
                });
#pragma warning restore 612, 618
        }
    }
}
